# Generated by Django 4.1.7 on 2023-05-15 18:31

from django.db import migrations, models
import imagehub.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagehub', '0003_tag_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=imagehub.models.upload_to),
        ),
    ]
